<script lang="ts">
  import { ArrowLeft, PencilSimple, Share } from 'phosphor-svelte';
  import Icon from '$lib/components/Icon.svelte';
  import { recipeJsonLd } from '$lib/jsonld';
  import { recipesApi } from '$lib/api';
  import type { PageProps } from './$types';

  let { data }: PageProps = $props();
  const recipe = $derived(data.recipe);

  // Build the JSON-LD object for the structured-data lesson.
  // Serialize once and inject via {@html} — see the comment on the
  // script tag below for why this is the right call.
  const pageUrl = $derived(`/recipes/${recipe.slug}`);
  const jsonLd = $derived(JSON.stringify(recipeJsonLd(recipe, pageUrl)));

  let shareUrl = $state<string | null>(null);
  let shareError = $state<string | null>(null);
  async function makeShare() {
    shareError = null;
    try {
      const link = await recipesApi.share(fetch, recipe.id);
      shareUrl = link.url;
    } catch (err) {
      shareError = (err as Error).message;
    }
  }
</script>

<svelte:head>
  <title>{recipe.title} — Recipes</title>
  <meta name="description" content={recipe.description || `Recipe for ${recipe.title}.`} />
  <!--
    Recipe JSON-LD. This is the structured-data block Google scans to
    populate rich-results (cards, cook time, image, ratings).

    WHY `{@html}`: the only way to put SCRIPT content in `<svelte:head>`.
    Svelte's normal text interpolation HTML-escapes everything, which
    would mangle the `"@type"` keys into `&quot;@type&quot;`. The
    content is generated by `recipeJsonLd` + `JSON.stringify`, both
    deterministic and never including user-controlled markup — only
    JSON-quoted strings — so there is no XSS vector here.

    See LESSON.md §A.3 for the full risk analysis.
  -->
  <!-- svelte-ignore-html-safe -->
  {@html `<script type="application/ld+json" id="recipe-jsonld">${jsonLd}</script>`}
</svelte:head>

<main>
  <a href="/" class="back"><Icon icon={ArrowLeft} size={16} /><span>All recipes</span></a>

  <article class="recipe">
    <header>
      <h1>{recipe.title}</h1>
      {#if recipe.description}<p class="desc">{recipe.description}</p>{/if}

      <dl class="tiles">
        {#if recipe.prep_minutes != null}
          <div><dt>Prep</dt><dd>{recipe.prep_minutes} min</dd></div>
        {/if}
        {#if recipe.cook_minutes != null}
          <div><dt>Cook</dt><dd>{recipe.cook_minutes} min</dd></div>
        {/if}
        {#if recipe.servings != null}
          <div><dt>Serves</dt><dd>{recipe.servings}</dd></div>
        {/if}
      </dl>

      <div class="actions">
        <a href="/recipes/{recipe.slug}/edit" class="link-button">
          <Icon icon={PencilSimple} size={16} />
          <span>Edit</span>
        </a>
        <button type="button" class="link-button" onclick={makeShare}>
          <Icon icon={Share} size={16} />
          <span>Make share link</span>
        </button>
      </div>
      {#if shareUrl}
        <p class="share-link" role="status">
          Share URL valid for 24h:
          <code data-testid="share-url">{shareUrl}</code>
        </p>
      {/if}
      {#if shareError}
        <p class="error" role="alert">{shareError}</p>
      {/if}
    </header>

    {#if recipe.images.length > 0}
      <section class="gallery" aria-label="Photos">
        {#each recipe.images as img (img.id)}
          <figure>
            <img
              src={img.url}
              alt={`${recipe.title} photo`}
              loading="lazy"
              width={img.width}
              height={img.height}
            />
          </figure>
        {/each}
      </section>
    {/if}

    <section aria-label="Ingredients" class="panel">
      <h2>Ingredients</h2>
      {#if recipe.ingredients.length === 0}
        <p class="empty">No ingredients listed yet.</p>
      {:else}
        <ul>
          {#each recipe.ingredients as ingredient, i (i)}
            <li>{ingredient}</li>
          {/each}
        </ul>
      {/if}
    </section>

    <section aria-label="Instructions" class="panel">
      <h2>Instructions</h2>
      {#if recipe.instructions.length === 0}
        <p class="empty">No instructions yet.</p>
      {:else}
        <ol>
          {#each recipe.instructions as step, i (i)}
            <li>{step}</li>
          {/each}
        </ol>
      {/if}
    </section>
  </article>
</main>

<style>
  main {
    max-width: var(--container-md);
    margin-inline: auto;
    padding: var(--space-6) var(--space-4);
    display: grid;
    gap: var(--space-5);
  }
  .back {
    display: inline-flex;
    align-items: center;
    gap: var(--space-1);
    color: var(--color-fg-muted);
    font-size: var(--text-sm);
  }
  .back:hover {
    color: var(--color-fg);
  }
  h1 {
    font-size: var(--text-3xl);
    font-weight: 800;
    line-height: var(--leading-tight);
  }
  .desc {
    color: var(--color-fg-muted);
    margin-top: var(--space-2);
  }
  .tiles {
    display: flex;
    flex-wrap: wrap;
    gap: var(--space-3);
    margin-top: var(--space-4);
    padding: var(--space-3);
    background: var(--color-bg-elev);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
  }
  .tiles > div {
    display: grid;
    gap: 2px;
    padding: var(--space-1) var(--space-3);
  }
  .tiles dt {
    color: var(--color-fg-muted);
    font-size: var(--text-xs);
    text-transform: uppercase;
    letter-spacing: 0.04em;
  }
  .tiles dd {
    font-size: var(--text-lg);
    font-weight: 700;
    font-variant-numeric: tabular-nums;
  }
  .actions {
    display: flex;
    gap: var(--space-3);
    margin-top: var(--space-4);
  }
  .link-button {
    display: inline-flex;
    align-items: center;
    gap: var(--space-2);
    padding: var(--space-2) var(--space-3);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    color: var(--color-fg);
    background: var(--color-bg);
    font-size: var(--text-sm);
    text-decoration: none;
  }
  .link-button:hover {
    border-color: var(--color-border-strong);
  }
  .share-link {
    margin-top: var(--space-3);
    padding: var(--space-3);
    background: var(--color-bg-sunken);
    border-radius: var(--radius-sm);
    font-size: var(--text-sm);
    overflow-wrap: anywhere;
  }
  .share-link code {
    font-family: var(--font-mono);
  }
  .error {
    margin-top: var(--space-3);
    padding: var(--space-3);
    color: var(--color-danger);
    background: hsl(0 72% 51% / 0.08);
    border: 1px solid hsl(0 72% 51% / 0.3);
    border-radius: var(--radius-md);
    font-size: var(--text-sm);
  }
  .gallery {
    display: grid;
    gap: var(--space-3);
  }
  .gallery figure {
    overflow: hidden;
    border-radius: var(--radius-md);
    border: 1px solid var(--color-border);
    background: var(--color-bg-sunken);
    aspect-ratio: 4 / 3;
  }
  .gallery img {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
  .panel {
    padding: var(--space-5);
    background: var(--color-bg-elev);
    border: 1px solid var(--color-border);
    border-radius: var(--radius-md);
    display: grid;
    gap: var(--space-3);
  }
  h2 {
    font-size: var(--text-lg);
    font-weight: 700;
  }
  .panel ul,
  .panel ol {
    padding-left: var(--space-5);
    display: grid;
    gap: var(--space-2);
  }
  .empty {
    color: var(--color-fg-muted);
  }
  @media (min-width: 768px) {
    main {
      padding: var(--space-12) var(--space-6);
    }
    .gallery {
      grid-template-columns: repeat(2, 1fr);
    }
  }
</style>
