/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

/**
 * Service worker — offline reading for recipes.
 *
 * Strategy:
 * 1. **Precache the SvelteKit build artifacts** (`build` + `files`)
 *    on `install`. This is the app shell — JS, CSS, fonts, the static
 *    favicon. Without these, the first reload after going offline
 *    would 404 the .js files and white-screen.
 * 2. **Cache visited recipe pages with a cache-first strategy** so a
 *    page the user has opened once is readable offline forever (well,
 *    until the next deploy invalidates it).
 * 3. **Version cache by `version`** from `$service-worker`. The
 *    SvelteKit build pipeline mints a fresh `version` for every
 *    build; bumping it bumps the cache key, and old caches get
 *    nuked in `activate`.
 *
 * `$service-worker` is a SvelteKit virtual module — it doesn't exist
 * as a file, the bundler synthesises it. You get `build` (files
 * generated by SvelteKit), `files` (everything in `static/`),
 * `prerendered` (prerendered pages), and `version` (deterministic
 * build id).
 */

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;
const CACHE = `recipes-cache-v${version}`;
const APP_SHELL = [...build, ...files];

sw.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      await cache.addAll(APP_SHELL);
      // Take over right away on first install so the next nav is
      // already serving from the SW.
      await sw.skipWaiting();
    })()
  );
});

sw.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await sw.clients.claim();
    })()
  );
});

sw.addEventListener('fetch', (event) => {
  // Skip cross-origin (API calls to the Rust backend, image uploads,
  // etc.) and non-GET requests.
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== sw.location.origin) return;

  // 1. App shell: cache-first.
  const isAppShellPath = APP_SHELL.includes(url.pathname);
  if (isAppShellPath) {
    event.respondWith(cacheFirst(event.request));
    return;
  }

  // 2. Recipe detail pages — cache after first visit (stale-while-revalidate-ish).
  if (url.pathname.startsWith('/recipes/') || url.pathname === '/') {
    event.respondWith(networkFirstWithCache(event.request));
    return;
  }

  // 3. Everything else passes through.
});

async function cacheFirst(req: Request): Promise<Response> {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(req);
  if (cached) return cached;
  const res = await fetch(req);
  if (res.ok) cache.put(req, res.clone());
  return res;
}

async function networkFirstWithCache(req: Request): Promise<Response> {
  const cache = await caches.open(CACHE);
  try {
    const res = await fetch(req);
    if (res.ok) cache.put(req, res.clone());
    return res;
  } catch {
    const cached = await cache.match(req);
    if (cached) return cached;
    return new Response(
      '<!doctype html><html><body><h1>Offline</h1><p>This recipe has not been cached for offline reading. Open it once online and it will be available next time.</p></body></html>',
      { status: 503, headers: { 'content-type': 'text/html' } }
    );
  }
}
